# site settings
title: Blanc Nacarat.
name: Blanc nacarat
type: label
subtitle: Records
email: nacarat.co@gmail.com
description: Blanc Nacarat Records<br> Label & Collectif artistique
# baseurl:  # the subpath of your site, e.g. /blog
# url: # the base hostname & protocol for your site
author: Blanc Nacarat
        twitter: blancnacarat
    
lang: fr_FR
street_address: 
city: 
state: 
zip_code:  
country: France
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0

# social settings
500px_url:
facebook_url: https://www.facebook.com/blanc.nacarat/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/blanc.nacarat/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/blancnacarat

# build settings
markdown: kramdown

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
