# site settings
title: Blanc Nacarat.
subtitle: Collectif
email: nacarat.co@gmail.com
description: Collectif artistique <br> petit désordre.
# baseurl:  # the subpath of your site, e.g. /blog
# url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code:  
country: France
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 0

# social settings
500px_url:
facebook_url: https://www.facebook.com/blanc.nacarat/
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/blanc.nacarat/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
